import React from "react";
import { Shield, Book, Mic, Send } from "lucide-react";
import { motion } from "framer-motion";

export function Dashboard() {
  return (
    <motion.main
      // This adds a smooth fade-in and slide-up animation when the dashboard loads
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.8, ease: "easeInOut" }}
      className="w-full max-w-7xl h-[85vh] bg-black/10 backdrop-blur-2xl border border-white/10 rounded-3xl shadow-2xl flex p-1"
    >
      {/* Left Panel: Intelligent Summary View (The "Sheet") */}
      <div className="w-7/12 p-8 overflow-y-auto">
        <h1 className="text-3xl font-bold mb-6 text-white">
          Intelligent Summary View
        </h1>
        <div className="bg-white/95 text-gray-800 p-8 rounded-xl shadow-lg h-full">
          <h2 className="text-xl font-semibold mb-1 text-black">
            Rental Agreement: Key Insights
          </h2>
          <p className="text-sm text-gray-500 mb-4">Generated by Veritas AI</p>

          <div className="border-l-4 border-red-500 pl-4 py-2 my-4 bg-red-500/10">
            <h3 className="font-bold text-red-700">
              High Risk: Uncapped Liability Clause
            </h3>
            <p className="text-sm text-red-800">
              You are liable for all damages without a specified limit. This is
              a significant financial risk.
            </p>
          </div>

          <h3 className="text-lg font-semibold mt-6 mb-3 text-black">
            Key Obligations
          </h3>
          <ul className="list-disc list-inside space-y-2 text-gray-700">
            <li>Tenant must provide a 60-day notice for termination.</li>
            <li>
              Security deposit is non-refundable if the lease is broken early.
            </li>
            <li>Subletting is strictly prohibited without written consent.</li>
          </ul>
        </div>
      </div>

      {/* Right Panel: AI Analysis Hub */}
      <div className="w-5/12 bg-black/20 rounded-r-3xl p-6 flex flex-col">
        <h2 className="text-2xl font-bold mb-4 text-white">AI Analysis Hub</h2>
        <div className="flex border-b border-white/20 mb-4">
          <button className="py-2 px-4 border-b-2 border-blue-500 text-white flex items-center gap-2">
            <Shield size={16} /> Risk Flags
          </button>
          <button className="py-2 px-4 text-gray-400 flex items-center gap-2">
            <Book size={16} /> Glossary
          </button>
        </div>

        <div className="space-y-3 flex-grow overflow-y-auto pr-2">
          {/* Risk Flag items will be mapped here from your API data */}
        </div>

        <div className="mt-auto">
          <div className="relative">
            <input
              type="text"
              placeholder="Ask about your document..."
              className="w-full bg-black/50 border border-white/20 rounded-full py-3 pl-6 pr-20 focus:outline-none focus:ring-2 focus:ring-blue-500 text-white"
            />
            <div className="absolute right-2 top-1/2 -translate-y-1/2 flex items-center gap-2">
              <button className="text-gray-400 hover:text-white">
                <Mic size={20} />
              </button>
              <button className="bg-blue-600 rounded-full p-2 text-white hover:bg-blue-500">
                <Send size={18} />
              </button>
            </div>
          </div>
        </div>
      </div>
    </motion.main>
  );
}
