import React from "react";
import { Canvas } from "@react-three/fiber";
import { ScalesOfJustice } from "./ScalesOfJustice";

export default function Dashboard() {
  return (
    <div
      style={{
        width: "100vw",
        height: "100vh",
        backgroundColor: "#1f2937",
        position: "relative",
        overflow: "hidden",
      }}
    >
      {/* 3D Canvas Background */}
      <Canvas
        camera={{
          position: [0, 0, 5],
          fov: 75,
        }}
        style={{
          width: "100%",
          height: "100%",
          position: "absolute",
          top: 0,
          left: 0,
          zIndex: 0,
        }}
      >
        <ambientLight intensity={1.2} />
        <directionalLight position={[5, 5, 5]} intensity={1.5} castShadow />
        <directionalLight position={[-5, 5, 5]} intensity={1} />
        <pointLight position={[0, 10, 5]} intensity={0.8} color="#ffffff" />
        <ScalesOfJustice />
      </Canvas>

      {/* UI Panels */}
      <div
        style={{
          position: "relative",
          zIndex: 10,
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          padding: "16px",
          gap: "24px",
        }}
      >
        {/* Left Panel - Document Analysis */}
        <div
          style={{
            width: "45%",
            height: "85vh",
            backgroundColor: "rgba(20, 20, 25, 0.05)",
            backdropFilter: "blur(3px)",
            border: "1px solid rgba(255, 255, 255, 0.2)",
            borderRadius: "24px",
            padding: "24px",
            color: "white",
            overflow: "auto",
          }}
        >
          <div
            style={{
              borderBottom: "1px solid rgba(255, 255, 255, 0.1)",
              paddingBottom: "16px",
              marginBottom: "24px",
            }}
          >
            <h2
              style={{
                fontSize: "24px",
                fontWeight: "bold",
                margin: "0 0 8px 0",
              }}
            >
              Intelligent Summary View
            </h2>
            <p style={{ fontSize: "14px", color: "#d1d5db", margin: 0 }}>
              Generated by LexiVerse AI
            </p>
          </div>

          <div style={{ marginBottom: "24px" }}>
            <h1
              style={{
                fontSize: "28px",
                fontWeight: "bold",
                margin: "0 0 12px 0",
              }}
            >
              Rental Agreement Analysis
            </h1>
            <div
              style={{
                width: "64px",
                height: "4px",
                backgroundColor: "#60a5fa",
                borderRadius: "2px",
              }}
            ></div>
          </div>

          <div
            style={{
              backgroundColor: "rgba(239, 68, 68, 0.2)",
              borderLeft: "4px solid #ef4444",
              padding: "16px",
              borderRadius: "8px",
              marginBottom: "24px",
            }}
          >
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: "8px",
                marginBottom: "8px",
              }}
            >
              <span
                style={{
                  color: "#fca5a5",
                  fontSize: "18px",
                  fontWeight: "bold",
                }}
              >
                ⚠ High Risk Identified
              </span>
            </div>
            <p style={{ color: "#fca5a5", lineHeight: "1.6", margin: 0 }}>
              <strong>Uncapped Liability Clause:</strong> The agreement contains
              provisions that make you liable for all damages without a
              specified limit. This represents significant financial exposure
              and should be negotiated.
            </p>
          </div>

          <div style={{ marginBottom: "24px" }}>
            <h3
              style={{
                fontSize: "20px",
                fontWeight: "bold",
                marginBottom: "16px",
              }}
            >
              Key Terms & Obligations
            </h3>

            <div
              style={{ display: "flex", flexDirection: "column", gap: "12px" }}
            >
              <div
                style={{
                  backgroundColor: "rgba(255, 255, 255, 0.1)",
                  border: "1px solid rgba(255, 255, 255, 0.15)",
                  borderRadius: "8px",
                  padding: "12px",
                }}
              >
                <h4
                  style={{
                    fontWeight: "bold",
                    margin: "0 0 4px 0",
                    color: "#e5e7eb",
                  }}
                >
                  Termination Notice
                </h4>
                <p style={{ fontSize: "14px", color: "#d1d5db", margin: 0 }}>
                  60-day written notice required for lease termination
                </p>
              </div>

              <div
                style={{
                  backgroundColor: "rgba(255, 255, 255, 0.1)",
                  border: "1px solid rgba(255, 255, 255, 0.15)",
                  borderRadius: "8px",
                  padding: "12px",
                }}
              >
                <h4
                  style={{
                    fontWeight: "bold",
                    margin: "0 0 4px 0",
                    color: "#e5e7eb",
                  }}
                >
                  Security Deposit
                </h4>
                <p style={{ fontSize: "14px", color: "#d1d5db", margin: 0 }}>
                  $5,000 deposit, non-refundable if lease broken early
                </p>
              </div>

              <div
                style={{
                  backgroundColor: "rgba(255, 255, 255, 0.1)",
                  border: "1px solid rgba(255, 255, 255, 0.15)",
                  borderRadius: "8px",
                  padding: "12px",
                }}
              >
                <h4
                  style={{
                    fontWeight: "bold",
                    margin: "0 0 4px 0",
                    color: "#e5e7eb",
                  }}
                >
                  Subletting Policy
                </h4>
                <p style={{ fontSize: "14px", color: "#d1d5db", margin: 0 }}>
                  Strictly prohibited without written landlord consent
                </p>
              </div>
            </div>
          </div>

          <div
            style={{
              backgroundColor: "rgba(59, 130, 246, 0.2)",
              border: "1px solid rgba(59, 130, 246, 0.3)",
              borderRadius: "8px",
              padding: "16px",
            }}
          >
            <h4
              style={{
                fontWeight: "bold",
                color: "#93c5fd",
                marginBottom: "12px",
              }}
            >
              Financial Summary
            </h4>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "1fr 1fr",
                gap: "12px",
                fontSize: "14px",
              }}
            >
              <div style={{ display: "flex", justifyContent: "space-between" }}>
                <span style={{ color: "#93c5fd" }}>Monthly Rent:</span>
                <span style={{ fontWeight: "bold" }}>$2,500</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between" }}>
                <span style={{ color: "#93c5fd" }}>Security Deposit:</span>
                <span style={{ fontWeight: "bold" }}>$5,000</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between" }}>
                <span style={{ color: "#93c5fd" }}>Late Fee:</span>
                <span style={{ fontWeight: "bold" }}>$150</span>
              </div>
              <div style={{ display: "flex", justifyContent: "space-between" }}>
                <span style={{ color: "#93c5fd" }}>Pet Deposit:</span>
                <span style={{ fontWeight: "bold" }}>$500</span>
              </div>
            </div>
          </div>
        </div>

        {/* Right Panel - AI Analysis Hub */}
        <div
          style={{
            width: "45%",
            height: "85vh",
            backgroundColor: "rgba(20, 20, 25, 0.05)",
            backdropFilter: "blur(2px)",
            border: "1px solid rgba(255, 255, 255, 0.2)",
            borderRadius: "24px",
            color: "white",
            display: "flex",
            flexDirection: "column",
          }}
        >
          {/* Header */}
          <div
            style={{
              padding: "24px",
              borderBottom: "1px solid rgba(75, 85, 99, 1)",
            }}
          >
            <h2
              style={{
                fontSize: "28px",
                fontWeight: "bold",
                margin: "0 0 8px 0",
              }}
            >
              AI Analysis Hub
            </h2>
            <p style={{ fontSize: "14px", color: "#9ca3af", margin: 0 }}>
              Intelligent legal document analysis
            </p>
          </div>

          {/* Tabs */}
          <div
            style={{
              display: "flex",
              borderBottom: "1px solid rgba(75, 85, 99, 1)",
            }}
          >
            <button
              style={{
                padding: "16px 24px",
                borderBottom: "2px solid #3b82f6",
                backgroundColor: "rgba(31, 41, 55, 0.5)",
                color: "white",
                border: "none",
                fontSize: "14px",
                fontWeight: "500",
                cursor: "pointer",
              }}
            >
              🛡️ Risk Flags
            </button>
            <button
              style={{
                padding: "16px 24px",
                color: "#9ca3af",
                backgroundColor: "transparent",
                border: "none",
                fontSize: "14px",
                cursor: "pointer",
              }}
            >
              📖 Glossary
            </button>
          </div>

          {/* Risk Analysis Options */}
          <div
            style={{
              flex: 1,
              padding: "24px",
              display: "flex",
              flexDirection: "column",
              gap: "12px",
              overflow: "auto",
              wordWrap: "break-word",
              overflowWrap: "break-word",
            }}
          >
            <div
              style={{
                backgroundColor: "rgba(239, 68, 68, 0.2)",
                border: "1px solid rgba(239, 68, 68, 0.5)",
                borderRadius: "8px",
                padding: "16px",
                cursor: "pointer",
              }}
            >
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                }}
              >
                <div
                  style={{ display: "flex", alignItems: "center", gap: "12px" }}
                >
                  <div
                    style={{
                      width: "12px",
                      height: "12px",
                      backgroundColor: "#ef4444",
                      borderRadius: "50%",
                    }}
                  ></div>
                  <span
                    style={{
                      fontSize: "14px",
                      fontWeight: "500",
                      wordWrap: "break-word",
                      overflowWrap: "break-word",
                      maxWidth: "200px",
                    }}
                  >
                    High Risk: Uncapped Liability
                  </span>
                </div>
                <span style={{ color: "#9ca3af" }}>👁️</span>
              </div>
            </div>

            <div
              style={{
                backgroundColor: "rgba(245, 158, 11, 0.2)",
                border: "1px solid rgba(245, 158, 11, 0.5)",
                borderRadius: "8px",
                padding: "16px",
                cursor: "pointer",
              }}
            >
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                }}
              >
                <div
                  style={{ display: "flex", alignItems: "center", gap: "12px" }}
                >
                  <div
                    style={{
                      width: "12px",
                      height: "12px",
                      backgroundColor: "#f59e0b",
                      borderRadius: "50%",
                    }}
                  ></div>
                  <span
                    style={{
                      fontSize: "14px",
                      fontWeight: "500",
                      wordWrap: "break-word",
                      overflowWrap: "break-word",
                      maxWidth: "200px",
                    }}
                  >
                    Medium: Early Termination Fee
                  </span>
                </div>
                <span style={{ color: "#9ca3af" }}>👁️</span>
              </div>
            </div>

            <div
              style={{
                backgroundColor: "rgba(249, 115, 22, 0.2)",
                border: "1px solid rgba(249, 115, 22, 0.5)",
                borderRadius: "8px",
                padding: "16px",
                cursor: "pointer",
              }}
            >
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                }}
              >
                <div
                  style={{ display: "flex", alignItems: "center", gap: "12px" }}
                >
                  <div
                    style={{
                      width: "12px",
                      height: "12px",
                      backgroundColor: "#f97316",
                      borderRadius: "50%",
                    }}
                  ></div>
                  <span
                    style={{
                      fontSize: "14px",
                      fontWeight: "500",
                      wordWrap: "break-word",
                      overflowWrap: "break-word",
                      maxWidth: "200px",
                    }}
                  >
                    Medium: No Pet Policy
                  </span>
                </div>
                <span style={{ color: "#9ca3af" }}>👁️</span>
              </div>
            </div>

            <div
              style={{
                backgroundColor: "rgba(34, 197, 94, 0.2)",
                border: "1px solid rgba(34, 197, 94, 0.5)",
                borderRadius: "8px",
                padding: "16px",
                cursor: "pointer",
              }}
            >
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                }}
              >
                <div
                  style={{ display: "flex", alignItems: "center", gap: "12px" }}
                >
                  <div
                    style={{
                      width: "12px",
                      height: "12px",
                      backgroundColor: "#22c55e",
                      borderRadius: "50%",
                    }}
                  ></div>
                  <span
                    style={{
                      fontSize: "14px",
                      fontWeight: "500",
                      wordWrap: "break-word",
                      overflowWrap: "break-word",
                      maxWidth: "200px",
                    }}
                  >
                    Low: Standard Maintenance Terms
                  </span>
                </div>
                <span style={{ color: "#9ca3af" }}>👁️</span>
              </div>
            </div>

            <div
              style={{
                backgroundColor: "rgba(59, 130, 246, 0.2)",
                border: "1px solid rgba(59, 130, 246, 0.5)",
                borderRadius: "8px",
                padding: "16px",
                cursor: "pointer",
              }}
            >
              <div
                style={{
                  display: "flex",
                  alignItems: "center",
                  justifyContent: "space-between",
                }}
              >
                <div
                  style={{ display: "flex", alignItems: "center", gap: "12px" }}
                >
                  <span style={{ color: "#60a5fa" }}>📄</span>
                  <span
                    style={{
                      fontSize: "14px",
                      fontWeight: "500",
                      wordWrap: "break-word",
                      overflowWrap: "break-word",
                      maxWidth: "200px",
                    }}
                  >
                    Generate Full Report
                  </span>
                </div>
                <span style={{ color: "#9ca3af" }}>👁️</span>
              </div>
            </div>
          </div>

          {/* Chat Input */}
          <div
            style={{
              padding: "24px",
              borderTop: "1px solid rgba(75, 85, 99, 1)",
            }}
          >
            <div
              style={{
                position: "relative",
                width: "100%",
                maxWidth: "100%",
                boxSizing: "border-box",
              }}
            >
              <input
                type="text"
                placeholder="Ask about your document..."
                style={{
                  width: "100%",
                  backgroundColor: "rgba(255, 255, 255, 0.05)",
                  border: "1px solid rgba(75, 85, 99, 1)",
                  borderRadius: "12px",
                  padding: "12px 80px 12px 16px",
                  color: "white",
                  fontSize: "14px",
                  outline: "none",
                  boxSizing: "border-box",
                  maxWidth: "100%",
                }}
              />
              <div
                style={{
                  position: "absolute",
                  right: "12px",
                  top: "50%",
                  transform: "translateY(-50%)",
                  display: "flex",
                  alignItems: "center",
                  gap: "8px",
                }}
              >
                <button
                  style={{
                    backgroundColor: "transparent",
                    border: "none",
                    color: "#9ca3af",
                    cursor: "pointer",
                    padding: "4px",
                  }}
                >
                  🎤
                </button>
                <button
                  style={{
                    backgroundColor: "#2563eb",
                    border: "none",
                    borderRadius: "8px",
                    padding: "8px",
                    color: "white",
                    cursor: "pointer",
                  }}
                >
                  ➤
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
